// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_rvULX4FBA1glOJ-VNg9wK2VlgP4Aj4',
    appId: '1:93734126620:web:4d1cae70a8715a9657cbd9',
    messagingSenderId: '93734126620',
    projectId: 'app-clima-anais',
    authDomain: 'app-clima-anais.firebaseapp.com',
    storageBucket: 'app-clima-anais.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4f-O5xPGQuWS1kfwYiSpmZkYAd_PgEg',
    appId: '1:93734126620:android:5ad22471effab6da57cbd9',
    messagingSenderId: '93734126620',
    projectId: 'app-clima-anais',
    storageBucket: 'app-clima-anais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGmCP7_Q8jGeqMdP7JL0FpkBONJCCJVvQ',
    appId: '1:93734126620:ios:e4abd12b7a6cb80a57cbd9',
    messagingSenderId: '93734126620',
    projectId: 'app-clima-anais',
    storageBucket: 'app-clima-anais.firebasestorage.app',
    iosBundleId: 'com.example.appClima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGmCP7_Q8jGeqMdP7JL0FpkBONJCCJVvQ',
    appId: '1:93734126620:ios:e4abd12b7a6cb80a57cbd9',
    messagingSenderId: '93734126620',
    projectId: 'app-clima-anais',
    storageBucket: 'app-clima-anais.firebasestorage.app',
    iosBundleId: 'com.example.appClima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh_rvULX4FBA1glOJ-VNg9wK2VlgP4Aj4',
    appId: '1:93734126620:web:9e2eb62495ff3e4457cbd9',
    messagingSenderId: '93734126620',
    projectId: 'app-clima-anais',
    authDomain: 'app-clima-anais.firebaseapp.com',
    storageBucket: 'app-clima-anais.firebasestorage.app',
  );

}